# Generated by Django 4.2.3 on 2024-10-17 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0002_alter_basicinfo_photo'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='countryID',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_countryID', to='basicinfo.countries', verbose_name='بلد الإقامة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genderID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.gender', verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userID',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
