# Generated by Django 4.2.3 on 2024-08-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='نشط'),
        ),
    ]
