# Generated by Django 4.2.3 on 2024-10-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0002_alter_basicinfo_photo'),
        ('profiles', '0002_userprofile_countryid_userprofile_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.gender', verbose_name='الجنس'),
        ),
    ]
