# Generated by Django 4.1.4 on 2023-01-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_ar', models.CharField(max_length=100, verbose_name='البنك عربي')),
                ('bank_en', models.CharField(max_length=100, verbose_name='البنك إنجليزي')),
                ('bank_Symbol', models.CharField(max_length=100, verbose_name=' رمز البنك')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ar', models.CharField(max_length=100, verbose_name='نوع العمل عربي')),
                ('type_en', models.CharField(max_length=100, verbose_name='نوع العمل إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_ar', models.CharField(max_length=50, verbose_name='الشهر عربي')),
                ('month_en', models.CharField(max_length=50, verbose_name='الشهر إنجليزي')),
                ('month_en_sort', models.CharField(max_length=50, verbose_name='إختصار الشهر إنجليزي')),
                ('daysOfMonth', models.CharField(max_length=50, verbose_name='أيام الشهر')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_ar', models.CharField(max_length=50, verbose_name='اليوم عربي')),
                ('day_en', models.CharField(max_length=50, verbose_name='اليوع إنجليزي')),
                ('day_short_en', models.CharField(max_length=50, verbose_name=' اليوع إنجليزي مختصر')),
                ('workDay', models.BooleanField(default=True, max_length=50, verbose_name='يوم عمل')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='العام')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName_ar', models.CharField(max_length=100, verbose_name='الإسم عربي')),
                ('compName_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم إنجليزي')),
                ('compAcronym_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر عربي')),
                ('compAcronym_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر إنجليزي')),
                ('compPhone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('compOwner', models.CharField(blank=True, max_length=100, null=True, verbose_name='المالك')),
                ('ownerPhone', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف المالك')),
                ('compEmail', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('compWebsite', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع الإلكتروني')),
                ('compAdministrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول')),
                ('compFax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فاكس')),
                ('compPOBox', models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق البري')),
                ('compRegionID', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة')),
                ('compCommercialRegister', models.CharField(blank=True, max_length=100, null=True, verbose_name='السجل التجاري')),
                ('compBusinessOfficeNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكتب العمل')),
                ('compWaselNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='واصل')),
                ('compZakatAndIncomeNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='الزكاء والضريبة')),
                ('compSocialSecurityNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='التأمينات الاجتماعية')),
                ('compChamberOfCommerceNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرفة التجارية')),
                ('compMunicipalAffairsNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='شؤون البلدية')),
                ('compNotes', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات')),
                ('compBankAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب')),
                ('compDocumentLink', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط المستندات')),
                ('who_i', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='profile')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='نشط')),
                ('businessTypeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.businesstype', verbose_name='نوع الشركة')),
                ('compbankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.bank', verbose_name='البنك')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName_ar', models.CharField(max_length=50, verbose_name='إسم الدولة عربي')),
                ('countryName_en', models.CharField(max_length=50, verbose_name='إسم الدولة إنجليزي')),
                ('code', models.CharField(max_length=50, verbose_name='الرمز الموحد')),
                ('callKey', models.CharField(max_length=50, verbose_name='مفتاح الإتصال')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية')),
            ],
        ),
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول عربي')),
                ('s_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني عربي')),
                ('t_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث عربي')),
                ('fo_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع عربي')),
                ('f_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول إنجليزي')),
                ('s_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني إنجليزي')),
                ('t_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث إنجليزي')),
                ('fo_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع إنجليزي')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('passportNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجواز')),
                ('passportExpiryDate', models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء الجواز')),
                ('borderNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحدود')),
                ('enteryDate', models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('businessOfficeNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم مكتب العمل')),
                ('mobileNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('iqamaNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإقامة')),
                ('iqamaReleaseDate', models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الإقامة')),
                ('iqamaExpiredDate', models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء الإقامة')),
                ('salaryInsurance', models.DecimalField(blank=True, decimal_places=2, default=400, max_digits=10, null=True, verbose_name='راتب التأمينات')),
                ('contractSalary', models.DecimalField(blank=True, decimal_places=2, default=1200, max_digits=10, null=True, verbose_name='راتب العق')),
                ('fixedExtra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='إضافي ثابت')),
                ('workStartingDate', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل')),
                ('endDateOfService', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل')),
                ('emp_Photograph', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='صورة شخصية')),
                ('coronaCheck', models.BooleanField(blank=True, default=True, null=True, verbose_name='فحص كرونا')),
                ('tawaklna', models.BooleanField(blank=True, default=True, null=True, verbose_name='توكلنا')),
                ('sahaty', models.BooleanField(blank=True, default=True, null=True, verbose_name='صحتي')),
                ('medicalInsurance', models.BooleanField(blank=True, default=True, null=True, verbose_name='تأمين طبي')),
                ('muqeemCopy', models.BooleanField(blank=True, default=True, null=True, verbose_name='نسخة مقيم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('documentLink', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط المستندات')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.bank', verbose_name='البنك')),
                ('companyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.company', verbose_name='الشركة')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_ar', models.CharField(max_length=50, verbose_name='الجنس عربي')),
                ('gender_en', models.CharField(max_length=50, verbose_name='الجنس إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName_ar', models.CharField(max_length=100, verbose_name='المشروع عربي')),
                ('proName_er', models.CharField(max_length=100, verbose_name='المشروع إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialStatus_ar', models.CharField(max_length=50, verbose_name='الحالة الإجتماعية عربي')),
                ('socialStatus_en', models.CharField(max_length=50, verbose_name='الحالة الإجتماعية إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingStatus_ar', models.CharField(max_length=100, verbose_name='حالة العمل عربي')),
                ('workingStatus_en', models.CharField(max_length=100, verbose_name='حالة العمل إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workSpecialty_ar', models.CharField(max_length=100, verbose_name='التخصص عربي')),
                ('workSpecialty_en', models.CharField(max_length=100, verbose_name='التخصص إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTrade_ar', models.CharField(max_length=100, verbose_name='المهنة عربي')),
                ('workTrade_en', models.CharField(max_length=100, verbose_name='المهنة إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noPro', models.CharField(default='1', max_length=100, verbose_name='رقم المشروع الفرعي ')),
                ('subProName_ar', models.CharField(max_length=100, verbose_name='مشروع فرعي عربي')),
                ('subProName_er', models.CharField(max_length=100, verbose_name='مشروع فرعي إنجليزي')),
                ('projectID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.project', verbose_name='المشروع الرئيس')),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsName', models.CharField(max_length=100, verbose_name='إسم الكفيل')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.company', verbose_name='الإسم الكامل')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntry', models.DateField(verbose_name='تاريخ الدخول')),
                ('dateExit', models.DateField(verbose_name='تاريخ الخروج')),
                ('workHours', models.IntegerField(default=0, verbose_name='ساعات العمل')),
                ('ExtraHours', models.IntegerField(default=0, verbose_name='الساعات الإضافية')),
                ('totalHours', models.IntegerField(default=0, verbose_name='إجمالي الساعات')),
                ('absentDays', models.IntegerField(default=0, verbose_name='أيام الغياب')),
                ('sellingPrice', models.IntegerField(default=0, verbose_name='سعر بيع الساعة')),
                ('purchasingPrice', models.IntegerField(default=0, verbose_name='سعر شراء الساعة')),
                ('otherAllowances', models.IntegerField(default=0, verbose_name='بدلات أخرى')),
                ('notesOtherAllowances', models.TextField(default=0, verbose_name='وصف البدلات')),
                ('otherDiscounts', models.IntegerField(default=0, verbose_name='خصومات أخرى')),
                ('notesOtherDiscounts', models.TextField(default=0, verbose_name='وصف الخصومات')),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.empinfo', verbose_name='العامل')),
                ('monthID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.calendarmonths', verbose_name='الشهر')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.project', verbose_name='المشروع')),
                ('subProjectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.subproject', verbose_name='مشروع فرعي')),
                ('yearID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.calendaryears', verbose_name='العام')),
            ],
            options={
                'verbose_name': 'دوران المشروع',
                'ordering': ['-projectID'],
            },
        ),
        migrations.AddField(
            model_name='empinfo',
            name='genderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.gender', verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='nationalityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.countries', verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='socialStatusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.socialstatus', verbose_name='الحالة لاغجتماعية'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='sponserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.sponser', verbose_name='الكفيل'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='workSpecialtyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.workspecialty', verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='workTradeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.worktrade', verbose_name='المهنة'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='workingStatusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.workingstatus', verbose_name='حالة العمل'),
        ),
        migrations.AddField(
            model_name='company',
            name='countryID',
            field=models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.countries', verbose_name='الدولة'),
        ),
    ]
