# Generated by Django 4.2.3 on 2024-08-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0001_initial'),
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('workStartDate', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل')),
                ('contractSalary', models.DecimalField(blank=True, decimal_places=2, default=1200, max_digits=10, null=True, verbose_name='راتب العقد')),
                ('fixedExtra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='إضافي ثابت')),
                ('workEndDate', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل')),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('personID', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.persons')),
                ('workingStatusID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workingstatus', verbose_name='حالة العمل')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntry', models.DateField(verbose_name='تاريخ الدخول')),
                ('dateExit', models.DateField(verbose_name='تاريخ الخروج')),
                ('workHours', models.IntegerField(default=0, verbose_name='ساعات العمل')),
                ('ExtraHours', models.IntegerField(default=0, verbose_name='الساعات الإضافية')),
                ('totalHours', models.IntegerField(default=0, verbose_name='إجمالي الساعات')),
                ('absentDays', models.IntegerField(default=0, verbose_name='أيام الغياب')),
                ('sellingPrice', models.IntegerField(default=0, verbose_name='سعر بيع الساعة')),
                ('purchasingPrice', models.IntegerField(default=0, verbose_name='سعر شراء الساعة')),
                ('otherAllowances', models.IntegerField(default=0, verbose_name='بدلات أخرى')),
                ('notesOtherAllowances', models.TextField(default=0, verbose_name='وصف البدلات')),
                ('otherDiscounts', models.IntegerField(default=0, verbose_name='خصومات أخرى')),
                ('notesOtherDiscounts', models.TextField(default=0, verbose_name='وصف الخصومات')),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employeeinfo', verbose_name='العامل')),
                ('monthID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.calendarmonths', verbose_name='الشهر')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.project', verbose_name='المشروع')),
                ('subProjectID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.subproject', verbose_name='مشروع فرعي')),
                ('yearID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.calendaryears', verbose_name='العام')),
            ],
        ),
    ]
