# Generated by Django 4.2.3 on 2023-08-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_remove_legalpersonality_bankaccount_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='workingStatusID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workingstatus', verbose_name='حالة العمل'),
        ),
    ]
