# Generated by Django 4.2.3 on 2024-07-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='companyID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company', verbose_name='الشركة'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
