# Generated by Django 4.2.3 on 2024-08-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_rename_legalpersonid_company_legalpersonid'),
        ('accounts', '0003_initial'),
        ('basicinfo', '0004_basicinfo_delete_alter_basicinfo_active'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeInfo',
            new_name='Employee',
        ),
    ]
