# Generated by Django 4.1.4 on 2023-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='emp_Photograph',
        ),
        migrations.AddField(
            model_name='empinfo',
            name='emp_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='صورة شخصية'),
        ),
    ]
