# Generated by Django 4.1.4 on 2023-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_empinfo_emp_photograph_empinfo_emp_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empinfo',
            old_name='borderNo',
            new_name='borderNumber',
        ),
        migrations.RenameField(
            model_name='empinfo',
            old_name='businessOfficeNo',
            new_name='businessOfficeNumber',
        ),
        migrations.RenameField(
            model_name='empinfo',
            old_name='iqamaNo',
            new_name='iqamaNumber',
        ),
        migrations.RenameField(
            model_name='empinfo',
            old_name='passportNo',
            new_name='passportNumber',
        ),
        migrations.AddField(
            model_name='empinfo',
            name='medicalInsuranceExpirDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء التأمين الطبي'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='visaNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التأشيرة'),
        ),
    ]
