# Generated by Django 4.2.3 on 2023-08-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_empinfo_workingstatusid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='lpID',
        ),
    ]
