# Generated by Django 4.2.3 on 2024-07-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_rename_notes_company_notes_alter_company_pobox_and_more'),
        ('basicinfo', '0006_person_created_at_person_created_by_and_more'),
        ('employees', '0002_alter_empinfo_companyid_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='companyID',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='personID',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='workingStatusID',
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('workStartDate', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل')),
                ('contractSalary', models.DecimalField(blank=True, decimal_places=2, default=1200, max_digits=10, null=True, verbose_name='راتب العقد')),
                ('fixedExtra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='إضافي ثابت')),
                ('workEndDate', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('personID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.person')),
                ('workingStatusID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workingstatus', verbose_name='حالة العمل')),
            ],
        ),
        migrations.AlterField(
            model_name='projectrotation',
            name='empID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employeeinfo', verbose_name='العامل'),
        ),
    ]
