# Generated by Django 4.1.4 on 2023-02-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_borderno_empinfo_bordernumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName_ar', models.CharField(max_length=50, verbose_name='إسم المنطقة عربي')),
                ('RegionName_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المنطقة إنجليزي')),
                ('countryID', models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='employees.countries', verbose_name='الدولة')),
            ],
        ),
    ]
