# Generated by Django 4.2.3 on 2024-07-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_empinfo_companyid_remove_empinfo_personid_and_more'),
        ('hadena', '0002_alter_contracts_witnes1id_alter_contracts_witnes2id_and_more'),
        ('accounts', '0005_alter_qayddetails_empid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpInfo',
        ),
    ]
