# Generated by Django 4.2.3 on 2023-08-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_company_company_lpid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empinfo',
            old_name='person',
            new_name='personID',
        ),
    ]
