# Generated by Django 4.1.4 on 2023-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_company_image_alter_company_who_i_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='capitalRegion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عاصمة المنطقة'),
        ),
        migrations.AddField(
            model_name='region',
            name='imageRegion',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name=' صورة للمنطقة'),
        ),
    ]
