# Generated by Django 4.1.4 on 2023-02-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_region_capitalregion_region_imageregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='countryID',
            field=models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.countries', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='project',
            name='directSupervisor',
            field=models.CharField(default=1, max_length=100, verbose_name='المشرف المباشر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='phoneDirectSupervisor',
            field=models.CharField(default=1, max_length=100, verbose_name='جوال المشرف المباشر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='regionID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة'),
        ),
    ]
