# Generated by Django 4.1.4 on 2023-02-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_project_countryid_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='RegionName_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المنطقة عربي'),
        ),
        migrations.AlterField(
            model_name='states',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد السكان'),
        ),
        migrations.AlterField(
            model_name='states',
            name='stateName_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المدينة عربي'),
        ),
        migrations.AlterField(
            model_name='states',
            name='stateName_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المدينة إنجليزي'),
        ),
    ]
