# Generated by Django 4.1.4 on 2023-02-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_region_regionname_ar_alter_states_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='regionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='states',
            name='stateName_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المحافظة عربي'),
        ),
        migrations.AlterField(
            model_name='states',
            name='stateName_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المحافظة إنجليزي'),
        ),
    ]
