# Generated by Django 4.1.4 on 2023-02-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_project_regionid_alter_states_statename_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='socialStatusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.socialstatus', verbose_name='الحالة الإجتماعية'),
        ),
        migrations.AlterField(
            model_name='sponser',
            name='companyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.company', verbose_name='الشركة'),
        ),
    ]
