# Generated by Django 4.1.4 on 2023-02-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_empinfo_socialstatusid_alter_sponser_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspecialty',
            name='workTradeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.worktrade', verbose_name='معرف المهنة'),
        ),
    ]
