# Generated by Django 4.1.4 on 2023-04-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_axis_branchbank_cities_typeaccbank_typeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='ShareholdersID',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='Witnes1ID',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='axisID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='bankID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='branchBankID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='cityID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='genderID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='marketerID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='nationalityID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='socialStatusID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='stateID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='typeAccBankID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='typeID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='workSpecialtyID',
        ),
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='workTradeID',
        ),
        migrations.DeleteModel(
            name='Axis',
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.DeleteModel(
            name='ShareholdersInfo',
        ),
    ]
