# Generated by Django 4.1.4 on 2023-04-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_contracts_shareholdersid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_Symbol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='البنك إنجليزي'),
        ),
        migrations.AlterField(
            model_name='branchbank',
            name='bank_Symbol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك'),
        ),
        migrations.AlterField(
            model_name='branchbank',
            name='branchBank_EN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قرع البنك إنجليزي'),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العمل إنجليزي'),
        ),
        migrations.AlterField(
            model_name='typeaccbank',
            name='TypeAccBank_EN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب إنجليزي'),
        ),
        migrations.AlterField(
            model_name='typeaccbank',
            name='bank_Symbol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك'),
        ),
        migrations.AlterField(
            model_name='typeid',
            name='typeID_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الهوية إنجليزي'),
        ),
        migrations.AlterField(
            model_name='workingstatus',
            name='workingStatus_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة العمل إنجليزي'),
        ),
        migrations.AlterField(
            model_name='workspecialty',
            name='workSpecialty_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص إنجليزي'),
        ),
        migrations.AlterField(
            model_name='workspecialty',
            name='workTradeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.worktrade', verbose_name='معرف المهنة'),
        ),
        migrations.AlterField(
            model_name='worktrade',
            name='workTrade_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة إنجليزي'),
        ),
    ]
