# Generated by Django 4.2.3 on 2023-08-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0026_alter_bondscatchpay_projectid_and_more'),
        ('basicinfo', '0001_initial'),
        ('employees', '0014_alter_bank_bank_symbol_alter_bank_bank_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarWeek',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='stateID',
        ),
        migrations.RemoveField(
            model_name='company',
            name='businessTypeID',
        ),
        migrations.RemoveField(
            model_name='company',
            name='compbankID',
        ),
        migrations.RemoveField(
            model_name='company',
            name='countryID',
        ),
        migrations.RemoveField(
            model_name='project',
            name='countryID',
        ),
        migrations.RemoveField(
            model_name='project',
            name='regionID',
        ),
        migrations.RemoveField(
            model_name='region',
            name='countryID',
        ),
        migrations.RemoveField(
            model_name='sponser',
            name='companyID',
        ),
        migrations.RemoveField(
            model_name='states',
            name='regionID',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='projectID',
        ),
        migrations.RemoveField(
            model_name='workspecialty',
            name='workTradeID',
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='bankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='branchBankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='cityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='companyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='genderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.gender', verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='nationalityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='socialStatusID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.socialstatus', verbose_name='الحالة الإجتماعية'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='sponserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.sponser', verbose_name='الكفيل'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='stateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='typeAccBankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='typeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeid', verbose_name='نوع الهوية'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='workSpecialtyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workspecialty', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='workTradeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.worktrade', verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='projectrotation',
            name='monthID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.calendarmonths', verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='projectrotation',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='projectrotation',
            name='subProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.subproject', verbose_name='مشروع فرعي'),
        ),
        migrations.AlterField(
            model_name='projectrotation',
            name='yearID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.calendaryears', verbose_name='العام'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BranchBank',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='CalendarMonths',
        ),
        migrations.DeleteModel(
            name='CalendarYears',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SocialStatus',
        ),
        migrations.DeleteModel(
            name='Sponser',
        ),
        migrations.DeleteModel(
            name='states',
        ),
        migrations.DeleteModel(
            name='SubProject',
        ),
        migrations.DeleteModel(
            name='TypeAccBank',
        ),
        migrations.DeleteModel(
            name='TypeID',
        ),
        migrations.DeleteModel(
            name='WorkSpecialty',
        ),
        migrations.DeleteModel(
            name='WorkTrade',
        ),
    ]
