# Generated by Django 4.2.3 on 2023-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_empinfo_ibannumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrotation',
            options={},
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='documentLink',
        ),
        migrations.AddField(
            model_name='empinfo',
            name='workEndDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل'),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='workStartDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العمل'),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='contractSalary',
            field=models.DecimalField(blank=True, decimal_places=2, default=1200, max_digits=10, null=True, verbose_name='راتب العقد'),
        ),
    ]
