# Generated by Django 4.2.3 on 2023-08-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0010_legalpersonality_remove_sponser_companyid_and_more'),
        ('employees', '0018_alter_empinfo_workingstatusid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم الضريبي')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.legalpersonality')),
            ],
        ),
        migrations.AddField(
            model_name='empinfo',
            name='companyID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.company', verbose_name='الشركة'),
        ),
    ]
