# Generated by Django 4.2.3 on 2024-08-02 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0009_alter_company_businesstypeid_delete_businesstype'),
        ('products', '0008_itemdetails_targetgroupid_and_more'),
        ('basicinfo', '0015_legalpersons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('legalPersonsID', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.legalpersons')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, default='فاتورة مشتريات جديدة', max_length=250, null=True, verbose_name='وصف الفاتورة')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات الفاتورة')),
                ('approve', models.BooleanField(blank=True, default=False, null=True, verbose_name='إعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_invoP', to=settings.AUTH_USER_MODEL)),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.suppliers', verbose_name='المورد')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_invoP', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='سعر الشراء')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='خصم مسموح به')),
                ('total_price_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر قبل الضريبة')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='نسبة الضريبة')),
                ('tax_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='قيمة الضريبة')),
                ('total_price_after_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر بعد الخصم')),
                ('invoiceHeadID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qayd_details', to='purchases.invoicehead')),
                ('itemsDetailstID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemdetails', verbose_name='المنتج')),
            ],
        ),
    ]
