# Generated by Django 4.2.3 on 2024-10-15 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0001_initial'),
        ('companys', '0001_initial'),
        ('inventorys', '0001_initial'),
        ('products', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesPurchasesBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=6, null=True, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True, verbose_name='سعر الشراء')),
                ('unit_price_estimated', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True, verbose_name='سعر الشراءتقديري')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='خصم مسموح به')),
                ('total_price_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر قبل الضريبة')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='نسبة الضريبة')),
                ('tax_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='قيمة الضريبة')),
                ('total_price_after_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر بعد الخصم')),
                ('total_price_local_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر عملة محلية ')),
                ('inventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventorys.inventory', verbose_name='المخزن')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('legalPersonID', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.legalpersons')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesPurchasesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='سعر الصرف')),
                ('description', models.TextField(blank=True, default='مشتريات', max_length=250, null=True, verbose_name='الوصف')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attach_purchases', verbose_name='المرفقات')),
                ('approve', models.BooleanField(blank=True, default=False, null=True, verbose_name='إعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_invoices_purchases', to=settings.AUTH_USER_MODEL)),
                ('currencyID', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='العملة')),
                ('details', models.ManyToManyField(blank=True, related_name='invoices_purchases', through='purchases.InvoicesPurchasesBody', to='products.items')),
                ('inventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventorys.inventory', verbose_name='المخزن')),
                ('salesRepID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='مندوب المبيعات')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_supplier', to='purchases.suppliers', verbose_name='المورد')),
                ('typeDeliveryID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typedelivery', verbose_name='طريقة التسليم')),
                ('typePaymentID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typepayment', verbose_name='طريقة الدفع')),
                ('typeTransactionID', models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_invoices_purchases', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل')),
            ],
        ),
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='invoiceHeadID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases_invoice', to='purchases.invoicespurchaseshead'),
        ),
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='itemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_details', to='products.items', verbose_name='المنتج'),
        ),
    ]
