# Generated by Django 4.2.3 on 2024-10-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('basicinfo', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='inventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.inventory', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='salesRepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='مندوب المبيعات'),
        ),
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_supplier', to='purchases.suppliers', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='typeDeliveryID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typedelivery', verbose_name='طريقة التسليم'),
        ),
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='typePaymentID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typepayment', verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='typeTransactionID',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
        migrations.AddField(
            model_name='invoicespurchaseshead',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_invoices_purchases', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل'),
        ),
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='inventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.inventory', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='invoiceHeadID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases_invoice', to='purchases.invoicespurchaseshead'),
        ),
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='itemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_details', to='products.items', verbose_name='المنتج'),
        ),
    ]
