# Generated by Django 4.2.3 on 2024-08-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_invoicespurchasesbody_invoicespurchaseshead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespurchaseshead',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_supplier', to='purchases.suppliers', verbose_name='المورد'),
        ),
    ]
