# Generated by Django 4.2.3 on 2024-08-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_invoicessalesbody_inventoryid_and_more'),
        ('purchases', '0004_alter_invoicespurchaseshead_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='inventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.inventory', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='total_price_local_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر عملة محلية '),
        ),
    ]
