# Generated by Django 4.2.3 on 2024-08-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_invoicespurchasesbody_inventoryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicespurchasesbody',
            name='unit_price_estimated',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='سعر الشراءتقديري'),
        ),
        migrations.AlterField(
            model_name='invoicespurchasesbody',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='سعر الشراء'),
        ),
    ]
