# Generated by Django 4.2.3 on 2024-08-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0013_alter_persons_languagesid_alter_persons_skillsid'),
        ('purchases', '0006_invoicespurchasesbody_unit_price_estimated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespurchaseshead',
            name='typeTransactionID',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
    ]
