# Generated by Django 4.2.3 on 2024-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_invoicespurchaseshead_typetransactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespurchasesbody',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='invoicespurchasesbody',
            name='unit_price_estimated',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True, verbose_name='سعر الشراءتقديري'),
        ),
    ]
