# Generated by Django 4.2.3 on 2024-09-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_invoicespurchasesbody_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespurchasesbody',
            name='invoiceHeadID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases_invoice', to='purchases.invoicespurchaseshead'),
        ),
    ]
