# Generated by Django 4.2.3 on 2024-09-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_alter_invoicespurchasesbody_invoiceheadid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicespurchaseshead',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attach_purchases', verbose_name='المرفقات'),
        ),
    ]
