# Generated by Django 4.2.3 on 2024-08-03 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' تصنيف الحساب عربي')),
                ('category_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=' تصنيف الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب عربي')),
                ('nature_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائمة عربي')),
                ('statement_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائمة نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب إنجليزي')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الحساب')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف الحساب')),
                ('is_can_pay', models.BooleanField(blank=True, null=True, verbose_name='إمكانية الدفع')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب عربي')),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Qayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, default='قيد يومية جديد', max_length=250, null=True, verbose_name='وصف القيد')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات القيد')),
                ('posted', models.BooleanField(blank=True, default=False, null=True, verbose_name='ترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='QaydDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_details', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='التاريخ')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='سعر الصرف')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='الكمية')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='دائن')),
                ('description_details', models.TextField(blank=True, default='تفاصيل قيد يومية جديد', max_length=250, null=True, verbose_name='وصف تفصيل القيد')),
                ('accountID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountstree', verbose_name='الحساب')),
                ('currencyID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='العملة')),
            ],
        ),
    ]
