# Generated by Django 4.2.3 on 2024-07-09 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hadena', '0001_initial'),
        ('basicinfo', '0002_typetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' تصنيف الحساب عربي')),
                ('category_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=' تصنيف الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب عربي')),
                ('nature_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائمة عربي')),
                ('statement_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائمة نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب إنجليزي')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الحساب')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف الحساب')),
                ('is_can_pay', models.BooleanField(verbose_name='إمكانية الدفع والتحصيل بهذا الحساب')),
                ('categoryID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcategory', verbose_name='تصنيف حساب ')),
                ('natureID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountnature', verbose_name='طبيعة الحساب')),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب عربي')),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Qayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, default='قيد يومية جديد', max_length=250, null=True, verbose_name='وصف القيد')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات القيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qayds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QaydDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_details', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='التاريخ')),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='سعر الصرف')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='الكمية')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='دائن')),
                ('description_details', models.TextField(blank=True, default='تفاصيل قيد يومية جديد', max_length=250, null=True, verbose_name='وصف تفصيل القيد')),
                ('accountID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountstree', verbose_name='الحساب')),
                ('currencyID', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='العملة')),
                ('cycleID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycleID', to='hadena.cycle', verbose_name='الدورة')),
                ('empID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.empinfo', verbose_name='الموظف')),
                ('projectID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.project', verbose_name='المشروع')),
                ('qaydID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qayd_details', to='accounts.qayd')),
                ('shareholdersID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='المساهم', to='hadena.shareholdersinfo', verbose_name='المساهم')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='qayds', through='accounts.QaydDetails', to='accounts.accountstree'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='typeTransactionID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_qayds', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='typeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='statementID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountstatement', verbose_name='القائمة'),
        ),
    ]
