# Generated by Django 4.1.1 on 2023-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Product_favorites',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
