# Generated by Django 4.2.3 on 2023-10-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائمة عربي')),
                ('statement_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائمة نجليزي')),
            ],
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='statementID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountstatement', verbose_name='القائمة'),
        ),
    ]
