# Generated by Django 4.2.3 on 2024-08-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0001_initial'),
        ('products', '0001_initial'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qayddetails',
            name='itemsDetailstID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemdetails', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='qayddetails',
            name='projectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.project', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='qayddetails',
            name='qaydID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qayd_details', to='accounts.qayd'),
        ),
        migrations.AddField(
            model_name='qayddetails',
            name='shareholdersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='المساهم', to='hadena.shareholdersinfo', verbose_name='المساهم'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='companyID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qayds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='qayds', through='accounts.QaydDetails', to='accounts.accountstree'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='typeTransactionID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_qayds', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='categoryID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcategory', verbose_name='تصنيف حساب '),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='natureID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountnature', verbose_name='طبيعة الحساب'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.accountstree', verbose_name='الحساب الأب'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='typeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='accountcategory',
            name='statementID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountstatement', verbose_name='القائمة'),
        ),
    ]
