# Generated by Django 4.1.4 on 2023-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0002_userprofile_product_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Product_favorites',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
