# Generated by Django 4.2.3 on 2024-08-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qayddetails',
            name='itemsDetailstID',
        ),
    ]
