# Generated by Django 4.2.3 on 2023-08-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0003_alter_userprofile_product_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Product_favorites',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
