# Generated by Django 4.2.3 on 2023-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_qayddetails_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qayd',
            name='details',
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='دائن'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مدين'),
        ),
    ]
