# Generated by Django 4.2.3 on 2023-12-30 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_qayd_details_alter_qayddetails_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qayd',
            name='userID',
        ),
        migrations.AddField(
            model_name='qayd',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qayd',
            name='created_py',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qayds', to=settings.AUTH_USER_MODEL, verbose_name='المُنشئ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(through='accounts.QaydDetails', to='accounts.accountstree'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='updated_dt',
            field=models.DateTimeField(null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='updated_py',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المُعدل'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 30, 9, 32, 27, 375222, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ القيد'),
        ),
    ]
