# Generated by Django 4.2.3 on 2024-08-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0013_alter_persons_languagesid_alter_persons_skillsid'),
        ('sales', '0022_alter_invoicessaleshead_customerid'),
        ('accounts', '0006_alter_accountstree_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='qayd',
            name='invoicesSalesID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoicessaleshead', verbose_name='فاتورة المبيعات'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='typeTransactionID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
    ]
