# Generated by Django 4.2.3 on 2023-12-30 14:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_remove_qayd_userid_qayd_created_dt_qayd_created_py_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 30, 14, 45, 18, 800169, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ القيد'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='updated_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='updated_py',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المُعدل'),
        ),
    ]
