# Generated by Django 4.2.3 on 2024-07-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_qayd_companyid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qayd',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='qayddetails',
            options={},
        ),
    ]
