# Generated by Django 4.2.3 on 2024-07-20 15:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstree',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountstree',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountstree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.accountstree'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountstree',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountstree',
            name='categoryID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcategory', verbose_name='تصنيف حساب '),
        ),
        migrations.AlterField(
            model_name='accountstree',
            name='is_can_pay',
            field=models.BooleanField(blank=True, null=True, verbose_name='إمكانية الدفع والتحصيل بهذا الحساب'),
        ),
        migrations.AlterField(
            model_name='accountstree',
            name='natureID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountnature', verbose_name='طبيعة الحساب'),
        ),
        migrations.AlterField(
            model_name='accountstree',
            name='typeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttype', verbose_name='نوع الحساب'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
