# Generated by Django 4.2.3 on 2024-07-22 04:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountstree_level_accountstree_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstree',
            name='is_can_pay',
            field=models.BooleanField(blank=True, null=True, verbose_name='إمكانية الدفع'),
        ),
        migrations.AlterField(
            model_name='accountstree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.accountstree', verbose_name='الحساب الأب'),
        ),
    ]
