# Generated by Django 4.2.3 on 2024-01-07 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_qayd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 7, 12, 38, 53, 101124, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ القيد'),
        ),
    ]
