# Generated by Django 4.2.3 on 2024-07-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_item_companyid_item_sequence_itemgrop_companyid_and_more'),
        ('basicinfo', '0007_color_size'),
        ('accounts', '0010_alter_accountstree_is_can_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qayd',
            name='posted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ترحيل'),
        ),
        migrations.AddField(
            model_name='qayddetails',
            name='itemsDetailstID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemsdetails', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='currencyID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='سعر الصرف'),
        ),
    ]
