# Generated by Django 4.2.3 on 2024-05-07 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_qayd_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qayddetails',
            old_name='description',
            new_name='description_details',
        ),
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 7, 20, 33, 55, 546457, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ القيد'),
        ),
    ]
