# Generated by Django 4.2.3 on 2024-06-28 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_description_qayddetails_description_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qayddetails',
            old_name='date',
            new_name='date_details',
        ),
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 6, 28, 2, 39, 56, 292381, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ القيد'),
        ),
    ]
