# Generated by Django 4.2.3 on 2024-07-03 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('accounts', '0015_rename_date_qayddetails_date_details_alter_qayd_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qayd',
            name='created_py',
        ),
        migrations.RemoveField(
            model_name='qayd',
            name='updated_py',
        ),
        migrations.AddField(
            model_name='qayd',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_qayds', to=settings.AUTH_USER_MODEL, verbose_name='المُنشئ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qayd',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_qayds', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ القيد'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='description',
            field=models.TextField(blank=True, default='قيد يومية جديد', max_length=250, null=True, verbose_name='وصف القيد'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='description_details',
            field=models.TextField(blank=True, default='تفاصيل قيد يومية جديد', max_length=250, null=True, verbose_name='وصف تفصيل القيد'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='empID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف'),
        ),
    ]
