# Generated by Django 4.2.3 on 2024-07-03 08:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_qayd_created_py_remove_qayd_updated_py_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ القيد'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='date_details',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='التاريخ'),
        ),
    ]
