# Generated by Django 4.2.3 on 2024-07-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_alter_qayd_date_alter_qayddetails_date_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qayds_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
