# Generated by Django 4.2.3 on 2024-07-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_qayd_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayddetails',
            name='qaydID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.qayd', verbose_name='رأس القيد'),
        ),
    ]
