# Generated by Django 4.2.3 on 2024-07-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_qayddetails_qaydid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayddetails',
            name='qaydID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.qayd'),
        ),
    ]
