# Generated by Django 4.2.3 on 2024-07-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_qayddetails_qaydid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qayd',
            old_name='created_dt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='qayd',
            name='updated_dt',
        ),
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(through='accounts.QaydDetails', to='accounts.accountstree'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='qayddetails',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='الكمية'),
        ),
    ]
