# Generated by Django 4.2.3 on 2024-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_created_dt_qayd_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, through='accounts.QaydDetails', to='accounts.accountstree'),
        ),
    ]
