# Generated by Django 4.2.3 on 2024-07-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('basicinfo', '0002_typetransaction'),
        # ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeContract_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقد عربي')),
                ('typeContract_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقد إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholdersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('someoneToReferTo', models.CharField(blank=True, max_length=100, null=True, verbose_name='شخص للرجوع إليه')),
                ('phoneSomeoneToReferTo', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف شخص للرجوع إليه')),
                ('personID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personID', to='basicinfo.person')),
                ('supervisorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='المشرف', to='employees.empinfo', verbose_name='المشرف')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_ar', models.CharField(max_length=100, verbose_name='الدورة عربي')),
                ('cycle_er', models.CharField(blank=True, max_length=100, null=True, verbose_name='الدورة إنجليزي')),
                ('directSupervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='المشرف المباشر')),
                ('phoneDirectSupervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='جوال المشرف المباشر')),
                ('cityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('countryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('regionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='المنطقة')),
                ('stateID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='الولاية')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfContract', models.DateField(blank=True, null=True, verbose_name='تاريخ العقد')),
                ('contractNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العقد')),
                ('numberOfShares', models.IntegerField(default=1, verbose_name='عدد الأسهم')),
                ('amountOfShare', models.IntegerField(default=1200000, verbose_name='سعر السهم')),
                ('profitRate', models.IntegerField(default=8, verbose_name='معدل الربح')),
                ('dateOfDividend', models.DateField(blank=True, null=True, verbose_name='تاريخ توزيع الأرباح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('cycleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hadena.cycle', verbose_name='الدورة')),
                ('receiptID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.qayd', verbose_name='رقم الإيصال')),
                ('shareholdersID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Shareholders', to='hadena.shareholdersinfo', verbose_name='المساهم')),
                ('typeContractID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hadena.typecontract', verbose_name='نوع العقد')),
                ('witnes1ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnes1ID', to='employees.empinfo', verbose_name='الشاهد الأول')),
                ('witnes2ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnes2ID', to='employees.empinfo', verbose_name='الشاهد الثاني')),
            ],
        ),
    ]
