# Generated by Django 4.2.3 on 2023-08-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_ar', models.CharField(max_length=100, verbose_name='المحور عربي')),
                ('axis_er', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحور إنجليزي')),
                ('directSupervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='المشرف المباشر')),
                ('phoneDirectSupervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='جوال المشرف المباشر')),
                ('cityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('countryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('regionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='المنطقة')),
                ('stateID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='الولاية')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholdersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.empinfo', verbose_name='المسووق')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfContract', models.DateField(blank=True, null=True, verbose_name='تاريخ العقد')),
                ('contractNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العقد')),
                ('numberReceipt', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال')),
                ('numberOfShares', models.IntegerField(default=1, verbose_name='عدد الأسهم')),
                ('amountOfShare', models.IntegerField(default=1200000, verbose_name='سعر السهم')),
                ('profitOfShare', models.IntegerField(default=8, verbose_name='ربح السهم')),
                ('dateOfDividend', models.DateField(blank=True, null=True, verbose_name='تاريخ توزيع الأرباح')),
                ('Witnes2ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Witnes2ID', to='employees.empinfo', verbose_name='الشاهد الثاني')),
                ('axisID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hadena.axis', verbose_name='المحور')),
                ('shareholdersID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Shareholders', to='hadena.shareholdersinfo', verbose_name='المساهم')),
                ('witnes1ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnes1ID', to='employees.empinfo', verbose_name='الشاهد الأول')),
            ],
        ),
    ]
