# Generated by Django 4.2.3 on 2023-08-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hadena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareholdersinfo',
            old_name='person',
            new_name='personID',
        ),
    ]
