# Generated by Django 4.2.3 on 2024-07-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_empinfo_companyid_remove_empinfo_personid_and_more'),
        ('hadena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='witnes1ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnes1ID', to='employees.employeeinfo', verbose_name='الشاهد الأول'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='witnes2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnes2ID', to='employees.employeeinfo', verbose_name='الشاهد الثاني'),
        ),
        migrations.AlterField(
            model_name='shareholdersinfo',
            name='supervisorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='المشرف', to='employees.employeeinfo', verbose_name='المشرف'),
        ),
    ]
