# Generated by Django 4.2.3 on 2023-10-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountstatement_accountcategory_statementid'),
        ('hadena', '0002_contracts_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='receiptID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.qayd', verbose_name='رقم الإيصال'),
        ),
    ]
