# Generated by Django 4.2.3 on 2023-09-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_rename_photo_person_photo'),
        ('gaccounts', '0003_bond_bonddetails_alter_qayddetails_desqayddetails_and_more'),
        ('employees', '0004_rename_person_empinfo_personid'),
        ('hadena', '0002_rename_person_shareholdersinfo_personid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_ar', models.CharField(max_length=100, verbose_name='الدورة عربي')),
                ('cycle_er', models.CharField(blank=True, max_length=100, null=True, verbose_name='الدورة إنجليزي')),
                ('directSupervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='المشرف المباشر')),
                ('phoneDirectSupervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='جوال المشرف المباشر')),
                ('cityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('countryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('regionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='المنطقة')),
                ('stateID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='الولاية')),
            ],
        ),
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeContract_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقد عربي')),
                ('typeContract_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العقد إنجليزي')),
            ],
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='Witnes2ID',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='axisID',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='numberReceipt',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='profitOfShare',
        ),
        migrations.AddField(
            model_name='contracts',
            name='ReceiptID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gaccounts.bond', verbose_name='رقم السند'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='profitRate',
            field=models.IntegerField(default=8, verbose_name='معدل الربح'),
        ),
        migrations.DeleteModel(
            name='Axis',
        ),
        migrations.AddField(
            model_name='contracts',
            name='cycleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hadena.cycle', verbose_name='الدورة'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='typeContractID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hadena.typecontract', verbose_name='نوع العقد'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='witnes2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnes2ID', to='employees.empinfo', verbose_name='الشاهد الثاني'),
        ),
    ]
