# Generated by Django 4.2.3 on 2023-12-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('hadena', '0003_alter_contracts_receiptid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholdersinfo',
            name='marketerID',
        ),
        migrations.AddField(
            model_name='shareholdersinfo',
            name='supervisorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='المشرف', to='employees.empinfo', verbose_name='المشرف'),
        ),
    ]
