# Generated by Django 4.2.3 on 2024-07-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_ar', models.CharField(max_length=100, verbose_name='البنك عربي')),
                ('bank_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='البنك إنجليزي')),
                ('bank_Symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك')),
            ],
        ),
        migrations.CreateModel(
            name='BranchBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchBank_AR', models.CharField(max_length=100, verbose_name='قرع البنك عربي')),
                ('branchBank_EN', models.CharField(blank=True, max_length=100, null=True, verbose_name='قرع البنك إنجليزي')),
                ('bank_Symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='معرف البنك')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ar', models.CharField(max_length=100, verbose_name='نوع العمل عربي')),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العمل إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_ar', models.CharField(max_length=50, verbose_name='الشهر عربي')),
                ('month_en', models.CharField(max_length=50, verbose_name='الشهر إنجليزي')),
                ('month_en_sort', models.CharField(max_length=50, verbose_name='إختصار الشهر إنجليزي')),
                ('daysOfMonth', models.CharField(max_length=50, verbose_name='أيام الشهر')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_ar', models.CharField(max_length=50, verbose_name='اليوم عربي')),
                ('day_en', models.CharField(max_length=50, verbose_name='اليوع إنجليزي')),
                ('day_short_en', models.CharField(max_length=50, verbose_name=' اليوع إنجليزي مختصر')),
                ('workDay', models.BooleanField(default=True, max_length=50, verbose_name='يوم عمل')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='العام')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المدينة عربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المدينة إنجليزي')),
                ('capitalCity', models.CharField(blank=True, max_length=50, null=True, verbose_name='عاصمةالمحلية')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='عدد السكان')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='إسم الدولة عربي')),
                ('name_en', models.CharField(max_length=50, verbose_name='إسم الدولة إنجليزي')),
                ('code', models.CharField(max_length=50, verbose_name='الرمز الموحد')),
                ('callKey', models.CharField(max_length=50, verbose_name='مفتاح الإتصال')),
                ('nationality_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية عربي')),
                ('nationality_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية إنجليزي')),
                ('currency_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='العملة عربي')),
                ('currency_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='العملة إنجليزي')),
                ('fractional_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='الكسر عربي')),
                ('fractional_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='الكسر إنجليزي')),
                ('symbol_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرمز عربي')),
                ('symbol_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرمز إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_ar', models.CharField(max_length=50, verbose_name='الجنس عربي')),
                ('gender_en', models.CharField(max_length=50, verbose_name='الجنس إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='المشروع عربي')),
                ('name_er', models.CharField(max_length=100, verbose_name='المشروع إنجليزي')),
                ('directSupervisor', models.CharField(max_length=100, verbose_name='المشرف المباشر')),
                ('phoneDirectSupervisor', models.CharField(max_length=100, verbose_name='جوال المشرف المباشر')),
                ('countryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المنطقة عربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المنطقة إنجليزي')),
                ('capitalRegion', models.CharField(blank=True, max_length=50, null=True, verbose_name='عاصمة المنطقة')),
                ('imageRegion', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name=' صورة للمنطقة')),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='معرف الدولة')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialStatus_ar', models.CharField(max_length=50, verbose_name='الحالة الإجتماعية عربي')),
                ('socialStatus_en', models.CharField(max_length=50, verbose_name='الحالة الإجتماعية إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAccBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeAccBank_AR', models.CharField(max_length=100, verbose_name='نوع الحساب عربي')),
                ('TypeAccBank_EN', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب إنجليزي')),
                ('bank_Symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك')),
            ],
        ),
        migrations.CreateModel(
            name='TypeID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeID_ar', models.CharField(max_length=100, verbose_name='نوع الهوية عربي')),
                ('typeID_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الهوية إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingStatus_ar', models.CharField(max_length=100, verbose_name='حالة العمل عربي')),
                ('workingStatus_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة العمل إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTrade_ar', models.CharField(max_length=100, verbose_name='المهنة عربي')),
                ('workTrade_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workSpecialty_ar', models.CharField(max_length=100, verbose_name='التخصص عربي')),
                ('workSpecialty_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص إنجليزي')),
                ('workTradeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.worktrade', verbose_name='معرف المهنة')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noPro', models.CharField(default='1', max_length=100, verbose_name='رقم المشروع الفرعي ')),
                ('name_ar', models.CharField(max_length=100, verbose_name='مشروع فرعي عربي')),
                ('name_er', models.CharField(max_length=100, verbose_name='مشروع فرعي إنجليزي')),
                ('projectID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.project', verbose_name='المشروع الرئيس')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم الولاية عربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم الولاية إنجليزي')),
                ('capitalState', models.CharField(blank=True, max_length=50, null=True, verbose_name='عاصمةالولاية')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='عدد السكان')),
                ('regionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='معرف المنطقة')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='regionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول عربي')),
                ('s_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني عربي')),
                ('t_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث عربي')),
                ('fo_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع عربي')),
                ('f_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول إنجليزي')),
                ('s_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني إنجليزي')),
                ('t_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث إنجليزي')),
                ('fo_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع إنجليزي')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهوية')),
                ('id_ExpiredDate', models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء الهوية')),
                ('desAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف عنوان السكن')),
                ('mobileNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('mobileNumberAnother', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم جوال آخر')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('IBANNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي')),
                ('ownerAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم صاحب الحساب')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='صورة شخصية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات')),
                ('documentLink', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط المستندات')),
                ('bankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
                ('branchBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك')),
                ('cityID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('countryID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countryID', to='basicinfo.countries', verbose_name='الدولة')),
                ('genderID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.gender', verbose_name='الجنس')),
                ('nationalityID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nationalityID', to='basicinfo.countries', verbose_name='الجنسية')),
                ('regionID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة')),
                ('socialStatusID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.socialstatus', verbose_name='الحالة الإجتماعية')),
                ('stateID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية')),
                ('typeAccBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب')),
                ('typeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeid', verbose_name='نوع الهوية')),
                ('workSpecialtyID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workspecialty', verbose_name='التخصص')),
                ('workTradeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.worktrade', verbose_name='المهنة')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الإسم عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم إنجليزي')),
                ('acronym_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر عربي')),
                ('acronym_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر إنجليزي')),
                ('regionID', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('IBANNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='المالك')),
                ('owner_Phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف المالك')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع الإلكتروني')),
                ('administrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فاكس')),
                ('POBox', models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق البري')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='شعار الشركة')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='نشط')),
                ('Notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
                ('branchBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك')),
                ('businessTypeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.businesstype', verbose_name='نوع الشركة')),
                ('countryID', models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('typeAccBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='stateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='معرف الولاية'),
        ),
    ]
