# Generated by Django 4.2.3 on 2023-08-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_ar', models.CharField(max_length=100, verbose_name='البنك عربي')),
                ('bank_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='البنك إنجليزي')),
                ('bank_Symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك')),
            ],
        ),
        migrations.CreateModel(
            name='BranchBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchBank_AR', models.CharField(max_length=100, verbose_name='قرع البنك عربي')),
                ('branchBank_EN', models.CharField(blank=True, max_length=100, null=True, verbose_name='قرع البنك إنجليزي')),
                ('bank_Symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ar', models.CharField(max_length=100, verbose_name='نوع العمل عربي')),
                ('type_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العمل إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_ar', models.CharField(max_length=50, verbose_name='الشهر عربي')),
                ('month_en', models.CharField(max_length=50, verbose_name='الشهر إنجليزي')),
                ('month_en_sort', models.CharField(max_length=50, verbose_name='إختصار الشهر إنجليزي')),
                ('daysOfMonth', models.CharField(max_length=50, verbose_name='أيام الشهر')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_ar', models.CharField(max_length=50, verbose_name='اليوم عربي')),
                ('day_en', models.CharField(max_length=50, verbose_name='اليوع إنجليزي')),
                ('day_short_en', models.CharField(max_length=50, verbose_name=' اليوع إنجليزي مختصر')),
                ('workDay', models.BooleanField(default=True, max_length=50, verbose_name='يوم عمل')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='العام')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName_ar', models.CharField(max_length=100, verbose_name='الإسم عربي')),
                ('compName_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم إنجليزي')),
                ('compAcronym_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر عربي')),
                ('compAcronym_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر إنجليزي')),
                ('compPhone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('compOwner', models.CharField(blank=True, max_length=100, null=True, verbose_name='المالك')),
                ('ownerPhone', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف المالك')),
                ('compEmail', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('compWebsite', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع الإلكتروني')),
                ('compAdministrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول')),
                ('compFax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فاكس')),
                ('compPOBox', models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق البري')),
                ('compRegionID', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة')),
                ('compCommercialRegister', models.CharField(blank=True, max_length=100, null=True, verbose_name='السجل التجاري')),
                ('compBusinessOfficeNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='مكتب العمل')),
                ('compWaselNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='واصل')),
                ('compZakatAndIncomeNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='الزكاء والضريبة')),
                ('compSocialSecurityNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='التأمينات الاجتماعية')),
                ('compChamberOfCommerceNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرفة التجارية')),
                ('compMunicipalAffairsNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='شؤون البلدية')),
                ('compNotes', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات')),
                ('compBankAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب')),
                ('compDocumentLink', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط المستندات')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='شعار الشركة')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='نشط')),
                ('businessTypeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.businesstype', verbose_name='نوع الشركة')),
                ('compbankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName_ar', models.CharField(max_length=50, verbose_name='إسم الدولة عربي')),
                ('countryName_en', models.CharField(max_length=50, verbose_name='إسم الدولة إنجليزي')),
                ('code', models.CharField(max_length=50, verbose_name='الرمز الموحد')),
                ('callKey', models.CharField(max_length=50, verbose_name='مفتاح الإتصال')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_ar', models.CharField(max_length=50, verbose_name='الجنس عربي')),
                ('gender_en', models.CharField(max_length=50, verbose_name='الجنس إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName_ar', models.CharField(max_length=100, verbose_name='المشروع عربي')),
                ('proName_er', models.CharField(max_length=100, verbose_name='المشروع إنجليزي')),
                ('directSupervisor', models.CharField(max_length=100, verbose_name='المشرف المباشر')),
                ('phoneDirectSupervisor', models.CharField(max_length=100, verbose_name='جوال المشرف المباشر')),
                ('countryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المنطقة عربي')),
                ('RegionName_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المنطقة إنجليزي')),
                ('capitalRegion', models.CharField(blank=True, max_length=50, null=True, verbose_name='عاصمة المنطقة')),
                ('imageRegion', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name=' صورة للمنطقة')),
                ('countryID', models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='معرف الدولة')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialStatus_ar', models.CharField(max_length=50, verbose_name='الحالة الإجتماعية عربي')),
                ('socialStatus_en', models.CharField(max_length=50, verbose_name='الحالة الإجتماعية إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAccBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeAccBank_AR', models.CharField(max_length=100, verbose_name='نوع الحساب عربي')),
                ('TypeAccBank_EN', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب إنجليزي')),
                ('bank_Symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز البنك')),
            ],
        ),
        migrations.CreateModel(
            name='TypeID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeID_ar', models.CharField(max_length=100, verbose_name='نوع الهوية عربي')),
                ('typeID_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الهوية إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTrade_ar', models.CharField(max_length=100, verbose_name='المهنة عربي')),
                ('workTrade_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workSpecialty_ar', models.CharField(max_length=100, verbose_name='التخصص عربي')),
                ('workSpecialty_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص إنجليزي')),
                ('workTradeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.worktrade', verbose_name='معرف المهنة')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noPro', models.CharField(default='1', max_length=100, verbose_name='رقم المشروع الفرعي ')),
                ('subProName_ar', models.CharField(max_length=100, verbose_name='مشروع فرعي عربي')),
                ('subProName_er', models.CharField(max_length=100, verbose_name='مشروع فرعي إنجليزي')),
                ('projectID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.project', verbose_name='المشروع الرئيس')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم الولاية عربي')),
                ('stateName_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم الولاية إنجليزي')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='عدد السكان')),
                ('regionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='معرف المنطقة')),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsName', models.CharField(max_length=100, verbose_name='إسم الكفيل')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.company', verbose_name='الشركة')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='regionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='company',
            name='countryID',
            field=models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة'),
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المدينة عربي')),
                ('cityName_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='إسم المدينة إنجليزي')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='عدد السكان')),
                ('stateID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='معرف الولاية')),
            ],
        ),
    ]
