# Generated by Django 4.2.3 on 2024-08-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='desAddress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='legalpersons',
            name='phoneAdmin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف الموظف المسؤول'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='صورة / لوقو'),
        ),
        migrations.AlterField(
            model_name='legalpersons',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='إسم الشركة عربي'),
        ),
        migrations.AlterField(
            model_name='legalpersons',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الشركة إنجليزي'),
        ),
    ]
