# Generated by Django 4.2.3 on 2024-01-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpersonality',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=2, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
    ]
