# Generated by Django 4.2.3 on 2023-08-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' العملة عربي')),
                ('currency_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=' العملة إنجليزي')),
                ('currencyCode', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز العملة')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingStatus_ar', models.CharField(max_length=100, verbose_name='حالة العمل عربي')),
                ('workingStatus_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة العمل إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول عربي')),
                ('s_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني عربي')),
                ('t_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث عربي')),
                ('fo_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع عربي')),
                ('f_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول إنجليزي')),
                ('s_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني إنجليزي')),
                ('t_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث إنجليزي')),
                ('fo_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع إنجليزي')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهوية')),
                ('detailsAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف عنوان السكن')),
                ('id_ExpiredDate', models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء الهوية')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('IBANNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي')),
                ('ownerAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم صاحب الحساب')),
                ('mobileNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('mobileNumberAnother', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم جوال آخر')),
                ('emp_Photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='صورة شخصية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
                ('branchBankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك')),
                ('cityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('companyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.company', verbose_name='الشركة')),
                ('genderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.gender', verbose_name='الجنس')),
                ('nationalityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الجنسية')),
                ('socialStatusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.socialstatus', verbose_name='الحالة الإجتماعية')),
                ('stateID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية')),
                ('typeAccBankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب')),
                ('typeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeid', verbose_name='نوع الهوية')),
                ('workSpecialtyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workspecialty', verbose_name='التخصص')),
                ('workTradeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.worktrade', verbose_name='المهنة')),
            ],
        ),
    ]
