# Generated by Django 4.2.3 on 2024-07-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTransaction_ar', models.CharField(max_length=100, verbose_name='نوع المعاملة عربي')),
                ('typeTransaction_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المعاملة إنجليزي')),
            ],
        ),
    ]
