# Generated by Django 4.2.3 on 2024-10-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_basicInfo', verbose_name='صورة / لوقو'),
        ),
    ]
