# Generated by Django 4.2.3 on 2024-07-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0002_typetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle_ar', models.CharField(max_length=100, verbose_name='المسمى الوظيفي عربي')),
                ('jobTitle_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي إنجليزي')),
            ],
        ),
        migrations.RemoveField(
            model_name='legalpersonality',
            name='bankID',
        ),
        migrations.RemoveField(
            model_name='legalpersonality',
            name='branchBankID',
        ),
        migrations.RemoveField(
            model_name='legalpersonality',
            name='businessTypeID',
        ),
        migrations.RemoveField(
            model_name='legalpersonality',
            name='countryID',
        ),
        migrations.RemoveField(
            model_name='legalpersonality',
            name='typeAccBankID',
        ),
    ]
