# Generated by Django 4.2.3 on 2024-08-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0002_rename_desaddress_basicinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpersons',
            name='basicInfoID',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_persons', to='basicinfo.basicinfo'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='basicInfoID',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='basicinfo.basicinfo'),
        ),
    ]
