# Generated by Django 4.2.3 on 2023-08-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0003_person_countryid_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='genderID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.gender', verbose_name='الجنس'),
        ),
    ]
