# Generated by Django 4.2.3 on 2024-07-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0003_jobtitle_remove_legalpersonality_bankid_and_more'),
        ('employees', '0002_alter_empinfo_companyid_delete_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalPersonality',
        ),
    ]
