# Generated by Django 4.2.3 on 2023-09-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0002_alter_qayd_currencyid'),
        ('basicinfo', '0003_remove_countries_currencycode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
