# Generated by Django 4.2.3 on 2024-08-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0003_alter_legalpersons_basicinfoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='نشط'),
        ),
    ]
