# Generated by Django 4.2.3 on 2023-08-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0004_alter_branchbank_bankid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalpersonality',
            name='BankAccount',
        ),
        migrations.AddField(
            model_name='legalpersonality',
            name='IBANNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي'),
        ),
        migrations.AddField(
            model_name='legalpersonality',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي'),
        ),
        migrations.AddField(
            model_name='legalpersonality',
            name='branchBankID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك'),
        ),
        migrations.AddField(
            model_name='legalpersonality',
            name='typeAccBankID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب'),
        ),
    ]
