# Generated by Django 4.2.3 on 2024-08-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0004_basicinfo_delete_alter_basicinfo_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='وحدة القياس عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='وحدة القياس إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='طريقة الدفع عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='طريقة الدفع إنجليزي')),
            ],
        ),
        migrations.RenameModel(
            old_name='DeliveryMethod',
            new_name='DeliveryMethods',
        ),
    ]
