# Generated by Django 4.2.3 on 2024-07-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0004_delete_legalpersonality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.RenameField(
            model_name='jobtitle',
            old_name='jobTitle_ar',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='jobtitle',
            old_name='jobTitle_en',
            new_name='name_en',
        ),
    ]
