# Generated by Django 4.2.3 on 2023-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_remove_legalpersonality_bankaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emp_Photo',
            new_name='Photo',
        ),
        migrations.AddField(
            model_name='person',
            name='documentLink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط المستندات'),
        ),
    ]
