# Generated by Django 4.2.3 on 2023-08-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_alter_person_bankid_alter_person_branchbankid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='regionID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='region',
            name='countryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='معرف الدولة'),
        ),
    ]
