# Generated by Django 4.2.3 on 2024-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_measuringunits_paymentmethods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='المخزن عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المخزن إنجليزي')),
            ],
        ),
    ]
