# Generated by Django 4.2.3 on 2023-09-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0006_rename_emp_photo_person_photo_person_documentlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Photo',
            new_name='photo',
        ),
    ]
