# Generated by Django 4.2.3 on 2024-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_measuringunitid_items_typeunitid'),
        ('sales', '0012_rename_measuringunitid_invoicessalesbody_typeunitid_and_more'),
        ('basicinfo', '0006_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryMethods',
            new_name='TypeDelivery',
        ),
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='TypePayment',
        ),
        migrations.RenameModel(
            old_name='MeasuringUnits',
            new_name='TypeUnit',
        ),
    ]
