# Generated by Django 4.2.3 on 2024-07-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0006_person_created_at_person_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_AR', models.CharField(max_length=100, verbose_name='اللون عربي')),
                ('name_EN', models.CharField(max_length=100, verbose_name='اللون إنجليزي')),
                ('color', models.CharField(default='#FFFFFF', help_text='Enter the color in hex format, e.g., #FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المقاس')),
                ('name_GB', models.CharField(max_length=100, verbose_name='مقاس المملكة المتحدة')),
                ('name_FR', models.CharField(max_length=100, verbose_name='مقاس فرنسا')),
                ('name_US', models.CharField(max_length=100, verbose_name='مقاس الولايات المتحدة')),
                ('name_DE', models.CharField(max_length=100, verbose_name='مقاس ألمانيا')),
                ('name_IT', models.CharField(max_length=100, verbose_name='مقاس إيطاليا')),
            ],
        ),
    ]
