# Generated by Django 4.2.3 on 2024-08-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_rename_deliverymethods_typedelivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اللون إنجليزي'),
        ),
    ]
