# Generated by Django 4.2.3 on 2024-07-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_color_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspecialty',
            old_name='workSpecialty_ar',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='workspecialty',
            old_name='workSpecialty_en',
            new_name='name_en',
        ),
    ]
