# Generated by Django 4.2.3 on 2023-08-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_alter_person_regionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='regionID',
        ),
    ]
