# Generated by Django 4.2.3 on 2024-07-31 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0009_rename_bank_symbol_bank_name_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='countryID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countryID', to='basicinfo.countries', verbose_name='بلد الإقامة'),
        ),
    ]
