# Generated by Django 4.2.3 on 2023-08-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0009_person_regionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الإسم عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم إنجليزي')),
                ('acronym_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر عربي')),
                ('acronym_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر إنجليزي')),
                ('regionID', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة')),
                ('BankAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='المالك')),
                ('owner_Phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف المالك')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع الإلكتروني')),
                ('administrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فاكس')),
                ('POBox', models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق البري')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='شعار الشركة')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='نشط')),
                ('Notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
                ('businessTypeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.businesstype', verbose_name='نوع الشركة')),
                ('countryID', models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
            ],
        ),
        migrations.RemoveField(
            model_name='sponser',
            name='companyID',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='detailsAddress',
            new_name='desAddress',
        ),
        migrations.RemoveField(
            model_name='person',
            name='companyID',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Sponser',
        ),
    ]
