# Generated by Django 4.2.3 on 2024-08-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_inventory_alter_invoicessaleshead_inventoryid'),
        ('basicinfo', '0010_alter_color_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
