# Generated by Django 4.2.3 on 2024-08-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0010_alter_person_countryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الفئة المستهدفة عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة المستهدفة إنجليزي')),
            ],
        ),
    ]
