# Generated by Django 4.2.3 on 2024-08-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0011_targetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='jobTitleID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
    ]
