# Generated by Django 4.2.3 on 2024-08-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0011_delete_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='bankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='branchBankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='cityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='regionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='stateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='typeAccBankID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='jobTitleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='languagesID',
            field=models.ManyToManyField(blank=True, null=True, to='basicinfo.languages', verbose_name='اللغات'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='skillsID',
            field=models.ManyToManyField(blank=True, null=True, to='basicinfo.skills', verbose_name='المهارات'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='workSpecialtyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.workspecialty', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='workTradeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.worktrade', verbose_name='المهنة'),
        ),
    ]
