# Generated by Django 4.2.3 on 2024-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0012_alter_basicinfo_bankid_alter_basicinfo_branchbankid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='languagesID',
            field=models.ManyToManyField(blank=True, to='basicinfo.languages', verbose_name='اللغات'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='skillsID',
            field=models.ManyToManyField(blank=True, to='basicinfo.skills', verbose_name='المهارات'),
        ),
    ]
