# Generated by Django 4.2.3 on 2024-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0012_person_jobtitleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اللغات عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اللغات إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='المهارات عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهارات إنجليزي')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='google_maps_location',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل'),
        ),
        migrations.AddField(
            model_name='person',
            name='languagesID',
            field=models.ManyToManyField(blank=True, default=1, to='basicinfo.languages', verbose_name='اللغات'),
        ),
        migrations.AddField(
            model_name='person',
            name='skillsID',
            field=models.ManyToManyField(blank=True, default=1, to='basicinfo.skills', verbose_name='المهارات'),
        ),
    ]
