# Generated by Django 4.2.3 on 2024-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0013_languages_skills_person_google_maps_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='نوع العمل عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العمل إنجليزي')),
            ],
        ),
    ]
