# Generated by Django 4.2.3 on 2024-09-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0014_businessscope_businessscopespecialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='countryID',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countryID', to='basicinfo.countries', verbose_name='بلد الإقامة'),
        ),
        migrations.AlterField(
            model_name='legalpersons',
            name='businessTypeID',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.businesstype', verbose_name='نوع الشركة'),
        ),
    ]
