# Generated by Django 4.2.3 on 2024-08-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0014_businesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الإسم عربي')),
                ('acronym_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم إنجليزي')),
                ('acronym_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر إنجليزي')),
                ('who_are_we', models.TextField(blank=True, max_length=250, null=True, verbose_name='من نحن')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف عنوان مقر الشركة')),
                ('google_maps_location', models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('IBANNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي')),
                ('accountName', models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب البنك بإسم')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('phoneOther', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم هاتف آخر')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع الإلكتروني')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فاكس')),
                ('POBox', models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق بريد')),
                ('administrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموظف المسؤول')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='شعار الشركة')),
                ('taxNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم الضريبي')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='نشط')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
                ('branchBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك')),
                ('businessTypeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.businesstype', verbose_name='نوع الشركة')),
                ('cityID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('countryID', models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('regionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة')),
                ('stateID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية')),
                ('typeAccBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب')),
            ],
        ),
    ]
