# Generated by Django 4.2.3 on 2024-08-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0015_legalpersons'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='طريقة التسليم عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='طريقة التسليم إنجليزي')),
            ],
        ),
    ]
