# Generated by Django 4.2.3 on 2024-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0019_alter_basicinfo_latitude_alter_basicinfo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attach_dalil', verbose_name='مرفقات'),
        ),
    ]
