# Generated by Django 4.2.3 on 2024-09-12 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0021_alter_basicinfo_cityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessscope',
            name='icone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='أيقونة المجال'),
        ),
        migrations.AddField(
            model_name='businessscope',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_businessScope', verbose_name='صورة / لوقو'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='cityID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basicInfo', to='basicinfo.cities', verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='legalpersons',
            name='basicInfoID',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalpersons', to='basicinfo.basicinfo'),
        ),
        migrations.AlterField(
            model_name='legalpersons',
            name='businessScopeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legalpersons', to='basicinfo.businessscope', verbose_name='مجال العمل'),
        ),
    ]
