# Generated by Django 4.2.3 on 2024-09-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0024_alter_basicinfo_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attach_basicInfo', verbose_name='مرفقات'),
        ),
    ]
