# Generated by Django 4.2.3 on 2024-09-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0025_alter_basicinfo_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attach_cities', verbose_name='مرفقات'),
        ),
    ]
