# Generated by Django 4.1.4 on 2023-04-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0013_remove_contracts_shareholdersid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_ar', models.CharField(max_length=100, verbose_name='المحور عربي')),
                ('axis_er', models.CharField(max_length=100, verbose_name='المحور إنجليزي')),
                ('directSupervisor', models.CharField(max_length=100, verbose_name='المشرف المباشر')),
                ('phoneDirectSupervisor', models.CharField(max_length=100, verbose_name='جوال المشرف المباشر')),
                ('countryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.countries', verbose_name='الدولة')),
                ('statesID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.states', verbose_name='المنطقة')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholdersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول عربي')),
                ('s_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني عربي')),
                ('t_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث عربي')),
                ('fo_Name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع عربي')),
                ('f_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الأول إنجليزي')),
                ('s_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثاني إنجليزي')),
                ('t_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الثالث إنجليزي')),
                ('fo_Name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم الرابع إنجليزي')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('mobileNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('mobileNumberAnother', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم جوال آخر')),
                ('detailsAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف عنوان السكن')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('IBANNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي')),
                ('ownerAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم صاحب الحساب')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهوية')),
                ('id_ExpiredDate', models.DateField(blank=True, null=True, verbose_name='تاريخ إنتهاء الهوية')),
                ('emp_Photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='صورة شخصية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('documentLink', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط المستندات')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.bank', verbose_name='البنك')),
                ('branchBankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.branchbank', verbose_name='فرع البنك')),
                ('cityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.cities', verbose_name='المدينة')),
                ('genderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.gender', verbose_name='الجنس')),
                ('marketerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.empinfo', verbose_name='المسووق')),
                ('nationalityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.countries', verbose_name='الجنسية')),
                ('socialStatusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.socialstatus', verbose_name='الحالة الإجتماعية')),
                ('stateID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.states', verbose_name='الولاية')),
                ('typeAccBankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.typeaccbank', verbose_name='نوع الحساب')),
                ('typeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.typeid', verbose_name='نوع الهوية')),
                ('workSpecialtyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.workspecialty', verbose_name='التخصص')),
                ('workTradeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.worktrade', verbose_name='المهنة')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='تاريخ العقد')),
                ('contractNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العقد')),
                ('numberReceipt', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال')),
                ('numberOfShares', models.IntegerField(default=1, verbose_name='عدد الأسهم')),
                ('amountOfShare', models.IntegerField(default=1200000, verbose_name='سعر السهم')),
                ('profitOfShare', models.IntegerField(default=135000, verbose_name='ربح السهم')),
                ('dateOfDividend', models.DateField(blank=True, null=True, verbose_name='تاريخ توزيع الأرباح')),
                ('axisID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shareholders.axis', verbose_name='المحور')),
                ('shareholdersID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shareholders.shareholdersinfo', verbose_name='المساهم')),
                ('witnes1ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.empinfo', verbose_name='الشاهد الأول')),
            ],
        ),
    ]
