# Generated by Django 4.1.4 on 2023-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='axis_er',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحور إنجليزي'),
        ),
        migrations.AlterField(
            model_name='axis',
            name='directSupervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المشرف المباشر'),
        ),
        migrations.AlterField(
            model_name='axis',
            name='phoneDirectSupervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جوال المشرف المباشر'),
        ),
    ]
