# Generated by Django 4.1.4 on 2023-04-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholders', '0002_alter_axis_axis_er_alter_axis_directsupervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareholdersinfo',
            old_name='emp_Photo',
            new_name='Photo',
        ),
    ]
