# Generated by Django 4.1.4 on 2023-04-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholders', '0003_rename_emp_photo_shareholdersinfo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='dateOfBirth',
            new_name='dateOfContract',
        ),
    ]
