# Generated by Django 4.2.3 on 2024-07-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicinfo', '0003_jobtitle_remove_legalpersonality_bankid_and_more'),
        ('profiles', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='إسم الشركة عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الشركة إنجليزي')),
                ('acronym_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر عربي')),
                ('acronym_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإسم المختصر إنجليزي')),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب المصرفي')),
                ('IBANNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الآيبان المصرفي')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='الإيميل')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع الإلكتروني')),
                ('administrator', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='فاكس')),
                ('POBox', models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق البري')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='شعار الشركة')),
                ('taxNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم الضريبي')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='نشط')),
                ('Notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات')),
                ('bankID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.bank', verbose_name='البنك')),
                ('branchBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.branchbank', verbose_name='فرع البنك')),
                ('countryID', models.ForeignKey(blank=True, default=13, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.userprofile', verbose_name='المالك')),
                ('regionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة')),
                ('typeAccBankID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typeaccbank', verbose_name='نوع الحساب')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='companys.company')),
                ('jobTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.jobtitle', verbose_name='المسمى الوظيفي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='profiles.userprofile')),
            ],
        ),
    ]
