# Generated by Django 4.2.3 on 2024-08-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LegalPersonID', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.legalpersons')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_companies', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companys', to='companys.company')),
                ('jobTitleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.jobtitle', verbose_name='المسمى الوظيفي')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userID', 'companyID')},
            },
        ),
    ]
