# Generated by Django 4.2.3 on 2024-08-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='LegalPersonID',
            new_name='legalPersonID',
        ),
    ]
