# Generated by Django 4.2.3 on 2024-09-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_rename_legalpersonid_company_legalpersonid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='includeInDalilAlaemal',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='تضمين في دليل الأعمال'),
        ),
        migrations.AddField(
            model_name='company',
            name='includeInInAccountingRecords',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='تضمين في السجلات المحاسبية'),
        ),
    ]
