# Generated by Django 4.2.3 on 2024-07-13 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_delete_businesstype_and_more'),
        ('companys', '0002_businesstype_rename_company_companyuser_companyid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='who_i',
        ),
        migrations.AddField(
            model_name='company',
            name='accountName',
            field=models.CharField(default=1, max_length=100, verbose_name='إسم الحساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف عنوان'),
        ),
        migrations.AddField(
            model_name='company',
            name='cityID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='company',
            name='phoneOther',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم هاتف آخر'),
        ),
        migrations.AddField(
            model_name='company',
            name='stateID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='company',
            name='who_are_we',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='من نحن'),
        ),
    ]
