# Generated by Django 4.2.3 on 2024-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_rename_image_company_logo_remove_company_who_i_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='company',
            name='POBox',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صندوق بريد'),
        ),
        migrations.AlterField(
            model_name='company',
            name='accountName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حساب البنك بإسم'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف عنوان مقر الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='administrator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الموظف المسؤول'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
