# Generated by Django 4.2.3 on 2024-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0005_alter_company_owner_alter_companyuser_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='google_maps_location',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل'),
        ),
    ]
