# Generated by Django 4.2.3 on 2024-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0005_alter_company_includeindalilalaemal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isDelivery',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='يوجد توصيل'),
        ),
    ]
