# Generated by Django 4.2.3 on 2024-08-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0014_businesstype'),
        ('companys', '0006_company_google_maps_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='businessTypeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.businesstype', verbose_name='نوع الشركة'),
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
    ]
