# Generated by Django 4.2.3 on 2024-09-12 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0022_businessscope_icone_businessscope_logo_and_more'),
        ('companys', '0006_company_isdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legalPersonID',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='basicinfo.legalpersons'),
        ),
    ]
