# Generated by Django 4.2.3 on 2024-08-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0007_alter_company_businesstypeid_delete_businesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='نوع العمل عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع العمل إنجليزي')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='businessTypeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='companys.businesstype', verbose_name='نوع الشركة'),
        ),
    ]
