# Generated by Django 4.2.3 on 2023-08-20 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('basicinfo', '0001_initial'),
        ('hadena', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accBudget_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' حساب الميزانية عربي')),
                ('accBudget_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=' حساب الميزانية نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccDorC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accDorC_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب عربي')),
                ('accDorC_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accName_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب عربي')),
                ('accName_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب إنجليزي')),
                ('accParentID', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحساب الأب')),
                ('accCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الحساب')),
                ('accDes', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الحساب')),
                ('is_can_pay', models.BooleanField(verbose_name='إمكانية الدفع والتحصيل بهذا الحساب')),
                ('accBudgetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accbudget', verbose_name='حساب الميزانية')),
                ('accDorCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accdorc', verbose_name='طبيعة الحساب')),
            ],
        ),
        migrations.CreateModel(
            name='AccType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accType_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب عربي')),
                ('accType_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Qayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateQayd', models.DateField(verbose_name='تاريخ القيد')),
                ('desQayd', models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف القيد')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات القيد')),
                ('currencyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.currency', verbose_name='العملة')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeBond_ar', models.CharField(max_length=100, verbose_name='نوع السند عربي')),
                ('typeBond_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع السند إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='QaydDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='دائن')),
                ('desQaydDetails', models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف تصفيل القيد')),
                ('accID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accountstree', verbose_name='الحساب')),
                ('empID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف')),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.project', verbose_name='المشروع')),
                ('qaydID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.qayd', verbose_name='رأس القيد')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(through='gaccounts.QaydDetails', to='gaccounts.accountstree'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='BondsCatchPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBond', models.DateField(verbose_name='تاريخ السند')),
                ('exchangeRate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الصرف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=100, verbose_name='الوصف')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم')),
                ('currencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.currency', verbose_name='العملة')),
                ('empID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف')),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.project', verbose_name='المشروع')),
                ('shareholderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hadena.shareholdersinfo', verbose_name='المساهم')),
                ('typeBondID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.typebond', verbose_name='نوع السند')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أمين الصندوق')),
            ],
        ),
        migrations.AddField(
            model_name='accountstree',
            name='accTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.acctype', verbose_name='نوع الحساب'),
        ),
    ]
