# Generated by Django 4.2.3 on 2023-09-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0003_remove_countries_currencycode_and_more'),
        ('gaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='currencyID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.countries', verbose_name='العملة'),
        ),
    ]
