# Generated by Django 4.1.4 on 2023-03-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstree',
            name='accBudgetID',
        ),
        migrations.RemoveField(
            model_name='accountstree',
            name='accCurrencyID',
        ),
        migrations.RemoveField(
            model_name='accountstree',
            name='accTypeID',
        ),
        migrations.RemoveField(
            model_name='qayd',
            name='details',
        ),
        migrations.RemoveField(
            model_name='qayd',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='qayddetails',
            name='accountID',
        ),
        migrations.RemoveField(
            model_name='qayddetails',
            name='empID',
        ),
        migrations.RemoveField(
            model_name='qayddetails',
            name='projectID',
        ),
        migrations.RemoveField(
            model_name='qayddetails',
            name='qaydID',
        ),
        migrations.DeleteModel(
            name='AccBudget',
        ),
        migrations.DeleteModel(
            name='AccountsTree',
        ),
        migrations.DeleteModel(
            name='AccType',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Qayd',
        ),
        migrations.DeleteModel(
            name='QaydDetails',
        ),
    ]
