# Generated by Django 4.2.3 on 2023-08-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_remove_legalpersonality_bankaccount_and_more'),
        ('employees', '0004_rename_person_empinfo_personid'),
        ('gaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='currencyID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.currency', verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='accID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accountstree', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='empID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='projectID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='qaydID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.qayd', verbose_name='رأس القيد'),
        ),
    ]
