# Generated by Django 4.1.4 on 2023-03-11 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0011_workspecialty_worktradeid'),
        ('gaccounts', '0002_remove_accountstree_accbudgetid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accBudget_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' حساب الميزانية عربي')),
                ('accBudget_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=' حساب الميزانية نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='AccountsTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accName_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب عربي')),
                ('accName_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='إسم الحساب إنجليزي')),
                ('accParentID', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحساب الأب')),
                ('accD_or_C', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب')),
                ('accCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الحساب')),
                ('is_can_pay', models.BooleanField(verbose_name='إمكانية الدفع والتحصيل بهذا الحساب')),
                ('accBudgetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accbudget', verbose_name='حساب الميزانية')),
            ],
        ),
        migrations.CreateModel(
            name='AccType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accType_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب عربي')),
                ('accType_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الحساب نجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name=' العملة عربي')),
                ('currency_en', models.CharField(blank=True, max_length=100, null=True, verbose_name=' العملة إنجليزي')),
                ('currencyCode', models.CharField(blank=True, max_length=100, null=True, verbose_name=' رمز العملة')),
            ],
        ),
        migrations.CreateModel(
            name='Qayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateQayd', models.DateTimeField(verbose_name='تاريخ القيد')),
                ('desQayd', models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف القيد')),
                ('attachments', models.FileField(upload_to='', verbose_name='مرفقات القيد')),
            ],
        ),
        migrations.CreateModel(
            name='QaydDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='دائن')),
                ('desQaydDetails', models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف تصفيل القيد')),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accountstree', verbose_name='الحساب')),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.project', verbose_name='المشروع')),
                ('qaydID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.qayd', verbose_name='رأس القيد')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(through='gaccounts.QaydDetails', to='gaccounts.accountstree'),
        ),
        migrations.AddField(
            model_name='qayd',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='accCurrencyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='accountstree',
            name='accTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.acctype', verbose_name='نوع الحساب'),
        ),
    ]
