# Generated by Django 4.2.3 on 2023-09-10 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_rename_photo_person_photo'),
        ('employees', '0004_rename_person_empinfo_personid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaccounts', '0002_alter_qayd_currencyid_alter_qayddetails_accid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السند')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف السند')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات السند')),
                ('typeID', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.typebond', verbose_name='نوع السند')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='BondDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ السند')),
                ('exchangeRate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الصرف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=100, verbose_name='الوصف')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم')),
                ('bondID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.bond', verbose_name='رأس السند')),
                ('currencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.currency', verbose_name='العملة')),
                ('empID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف')),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.project', verbose_name='المشروع')),
            ],
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='desQaydDetails',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='وصف تفصيل القيد'),
        ),
        migrations.DeleteModel(
            name='BondsCatchPay',
        ),
    ]
