# Generated by Django 4.1.4 on 2023-03-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccDorC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accDorC_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب عربي')),
                ('accDorC_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبيعة الحساب نجليزي')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountstree',
            name='accD_or_C',
        ),
    ]
