# Generated by Django 4.1.4 on 2023-03-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0004_accdorc_remove_accountstree_accd_or_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstree',
            name='AccDorCID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accdorc', verbose_name='طبيعة الحساب'),
            preserve_default=False,
        ),
    ]
