# Generated by Django 4.1.4 on 2023-03-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0005_accountstree_accdorcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstree',
            name='AccDorCID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accdorc', verbose_name='طبيعة الحساب'),
        ),
    ]
