# Generated by Django 4.1.4 on 2023-03-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0008_alter_accountstree_accdorcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstree',
            name='accDes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الحساب'),
        ),
        migrations.AlterField(
            model_name='accountstree',
            name='AccDorCID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accdorc', verbose_name='طبيعة الحساب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دائن'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='مدين'),
        ),
    ]
