# Generated by Django 4.1.4 on 2023-03-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0009_accountstree_accdes_alter_accountstree_accdorcid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountstree',
            old_name='AccDorCID',
            new_name='accDorCID',
        ),
    ]
