# Generated by Django 4.1.4 on 2023-03-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0010_rename_accdorcid_accountstree_accdorcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstree',
            name='accCurrencyID',
        ),
        migrations.AddField(
            model_name='qayd',
            name='accCurrencyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.currency', verbose_name='العملة'),
            preserve_default=False,
        ),
    ]
