# Generated by Django 4.1.4 on 2023-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0011_remove_accountstree_acccurrencyid_qayd_acccurrencyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='dateQayd',
            field=models.DateField(verbose_name='تاريخ القيد'),
        ),
    ]
