# Generated by Django 4.1.4 on 2023-03-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_workspecialty_worktradeid'),
        ('gaccounts', '0012_alter_qayd_dateqayd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفقات القيد'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='دائن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='مدين'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='empID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='projectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.project', verbose_name='المشروع'),
        ),
    ]
