# Generated by Django 4.1.4 on 2023-03-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0013_alter_qayd_attachments_alter_qayddetails_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qayd',
            old_name='accCurrencyID',
            new_name='currencyID',
        ),
        migrations.RenameField(
            model_name='qayddetails',
            old_name='accountID',
            new_name='accID',
        ),
    ]
