# Generated by Django 4.1.4 on 2023-05-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0014_rename_acccurrencyid_qayd_currencyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayd',
            name='currencyID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.currency', verbose_name='العملة'),
        ),
    ]
