# Generated by Django 4.1.4 on 2023-06-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0016_alter_qayd_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qayd',
            name='details',
        ),
    ]
