# Generated by Django 4.1.4 on 2023-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0017_remove_qayd_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(through='gaccounts.QaydDetails', to='gaccounts.accountstree'),
        ),
    ]
