# Generated by Django 4.2.3 on 2023-07-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0018_qayd_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qayd',
            name='details',
        ),
    ]
