# Generated by Django 4.2.3 on 2023-08-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0021_alter_qayd_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondsCatch_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBond', models.DateField(verbose_name='تاريخ السند')),
                ('exchangeRate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الصرف')),
                ('currencyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.currency', verbose_name='العملة')),
            ],
        ),
    ]
