# Generated by Django 4.2.3 on 2023-08-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0022_bondscatch_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qayddetails',
            name='accID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaccounts.accountstree', verbose_name='الحساب'),
        ),
    ]
