# Generated by Django 4.2.3 on 2023-08-17 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadena', '__first__'),
        ('employees', '0014_alter_bank_bank_symbol_alter_bank_bank_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaccounts', '0023_alter_qayddetails_accid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeBond_ar', models.CharField(max_length=100, verbose_name='نوع السند عربي')),
                ('typeBond_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع السند إنجليزي')),
            ],
        ),
        migrations.AlterField(
            model_name='qayd',
            name='details',
            field=models.ManyToManyField(through='gaccounts.QaydDetails', to='gaccounts.accountstree'),
        ),
        migrations.CreateModel(
            name='BondsCatchPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBond', models.DateField(verbose_name='تاريخ السند')),
                ('exchangeRate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الصرف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=100, verbose_name='الوصف')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم')),
                ('currencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.currency', verbose_name='العملة')),
                ('empID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.empinfo', verbose_name='الموظف')),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.project', verbose_name='المشروع')),
                ('shareholderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hadena.shareholdersinfo', verbose_name='المساهم')),
                ('typeBondID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaccounts.typebond', verbose_name='نوع السند')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أمين الصندوق')),
            ],
        ),
    ]
