# Generated by Django 4.2.3 on 2023-08-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaccounts', '0024_typebond_alter_qayd_details_bondscatchpay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BondsCatch_Pay',
        ),
    ]
