# Generated by Django 4.2.3 on 2023-08-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0001_initial'),
        ('gaccounts', '0025_delete_bondscatch_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondscatchpay',
            name='projectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='qayddetails',
            name='projectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.project', verbose_name='المشروع'),
        ),
    ]
