# Generated by Django 4.2.3 on 2023-08-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0002_currency_workingstatus_person'),
        ('gaccounts', '0026_alter_bondscatchpay_projectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondscatchpay',
            name='currencyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinfo.currency', verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='qayd',
            name='currencyID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.currency', verbose_name='العملة'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
