# Generated by Django 4.2.3 on 2024-08-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='itemsDetailsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemdetails'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='itemsDetailsID',
            field=models.ManyToManyField(through='orders.OrderDetails', to='products.itemdetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
