# Generated by Django 4.2.3 on 2024-07-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='productID',
        ),
    ]
