# Generated by Django 4.2.3 on 2024-08-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemsDetailsID',
            new_name='itemID',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='itemsDetailsID',
            new_name='itemID',
        ),
    ]
