# Generated by Django 4.2.3 on 2024-07-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_details_remove_orderdetails_productid'),
        ('products', '0002_category_categorytype_items_itemsdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsDetailsID',
            field=models.ManyToManyField(through='orders.OrderDetails', to='products.itemsdetails'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='itemsDetailsID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.itemsdetails'),
            preserve_default=False,
        ),
    ]
