# Generated by Django 4.2.3 on 2024-10-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0001_initial'),
        ('employees', '0001_initial'),
        ('basicinfo', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('legalPersonID', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basicinfo.legalpersons')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='المخزن عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المخزن إنجليزي')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف العنوان')),
                ('google_maps_location', models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل')),
                ('phoneAdmin', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف الموظف المسؤول')),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='الموظف المسؤول')),
                ('cityID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.cities', verbose_name='المدينة')),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='companys.company')),
                ('countryID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='الدولة')),
                ('regionID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.region', verbose_name='المنطقة')),
                ('stateID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.states', verbose_name='الولاية')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=6, null=True, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='سعر البيع')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='خصم مسموح به')),
                ('total_price_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر قبل الضريبة')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='نسبة الضريبة')),
                ('tax_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='قيمة الضريبة')),
                ('total_price_after_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر بعد الضريبة')),
                ('total_price_local_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر عملة محلية ')),
                ('inventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.inventory', verbose_name='المخزن')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesSalesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='سعر الصرف')),
                ('description', models.TextField(blank=True, default='مبيعات', max_length=250, null=True, verbose_name='الوصف')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان المستلم')),
                ('google_maps_location', models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم هاتف المستلم')),
                ('phoneOther', models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف آخر')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attach_sales', verbose_name='المرفقات')),
                ('approve', models.BooleanField(blank=True, default=False, null=True, verbose_name='إعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='companys.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_invoS', to=settings.AUTH_USER_MODEL)),
                ('currencyID', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='العملة')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_customer', to='sales.customers', verbose_name='العميل')),
                ('details', models.ManyToManyField(blank=True, related_name='invoices', through='sales.InvoicesSalesBody', to='products.items')),
                ('inventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.inventory', verbose_name='المخزن')),
                ('salesRepID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='مندوب المبيعات')),
                ('typeDeliveryID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typedelivery', verbose_name='طريقة التسليم')),
                ('typePaymentID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typepayment', verbose_name='طريقة الدفع')),
                ('typeTransactionID', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_invoS', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل')),
            ],
        ),
        migrations.AddField(
            model_name='invoicessalesbody',
            name='invoiceHeadID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_invoice', to='sales.invoicessaleshead'),
        ),
        migrations.AddField(
            model_name='invoicessalesbody',
            name='itemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_details', to='products.items', verbose_name='المنتج'),
        ),
    ]
