# Generated by Django 4.2.3 on 2024-08-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_measuringunits_paymentmethods_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoicehead',
            name='paymentMethodID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.paymentmethods', verbose_name='طريقة الدفع'),
            preserve_default=False,
        ),
    ]
