# Generated by Django 4.2.3 on 2024-08-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesinvoicehead_paymentmethodid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='legalPersonsID',
            new_name='legalPersonID',
        ),
        migrations.RenameField(
            model_name='salesinvoicebody',
            old_name='itemsDetailstID',
            new_name='itemID',
        ),
    ]
