# Generated by Django 4.2.3 on 2024-08-06 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_itemdetails_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0005_measuringunits_paymentmethods_and_more'),
        ('companys', '0002_rename_legalpersonid_company_legalpersonid'),
        ('sales', '0003_rename_legalpersonsid_customers_legalpersonid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesInvoiceBody',
            new_name='InvoicesSalesBody',
        ),
        migrations.RenameModel(
            old_name='SalesInvoiceHead',
            new_name='InvoicesSalesHead',
        ),
    ]
