# Generated by Django 4.2.3 on 2024-08-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_measuringunits_paymentmethods_and_more'),
        ('sales', '0007_remove_invoicessaleshead_measuringunitid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='deliveryMethodID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.deliverymethods', verbose_name='طريقة التسليم'),
        ),
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='paymentMethodID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.paymentmethods', verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='typeTransactionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
    ]
