# Generated by Django 4.2.3 on 2024-08-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_invoicessaleshead_deliverymethodid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicessaleshead',
            old_name='supplierID',
            new_name='customerID',
        ),
    ]
