# Generated by Django 4.2.3 on 2024-08-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0006_inventory'),
        ('sales', '0010_alter_invoicessalesbody_measuringunitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessaleshead',
            name='inventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.inventory', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='invoicessalesbody',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='خصم مسموح به'),
        ),
        migrations.AlterField(
            model_name='invoicessalesbody',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='سعر البيع'),
        ),
    ]
