# Generated by Django 4.2.3 on 2024-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_invoicessaleshead_inventoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicessalesbody',
            old_name='measuringUnitID',
            new_name='typeUnitID',
        ),
        migrations.RenameField(
            model_name='invoicessaleshead',
            old_name='deliveryMethodID',
            new_name='typedeliveryID',
        ),
        migrations.RenameField(
            model_name='invoicessaleshead',
            old_name='paymentMethodID',
            new_name='typepaymentID',
        ),
    ]
