# Generated by Django 4.2.3 on 2024-08-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_rename_deliverymethods_typedelivery_and_more'),
        ('sales', '0012_rename_measuringunitid_invoicessalesbody_typeunitid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicessalesbody',
            name='typeUnitID',
        ),
        migrations.RemoveField(
            model_name='invoicessaleshead',
            name='typedeliveryID',
        ),
        migrations.RemoveField(
            model_name='invoicessaleshead',
            name='typepaymentID',
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='typeDeliveryID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typedelivery', verbose_name='طريقة التسليم'),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='typePaymentID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typepayment', verbose_name='طريقة الدفع'),
        ),
    ]
