# Generated by Django 4.2.3 on 2024-08-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_items_itemgropid_alter_items_typeunitid'),
        ('basicinfo', '0007_rename_deliverymethods_typedelivery_and_more'),
        ('sales', '0013_remove_invoicessalesbody_typeunitid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessaleshead',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='invoices', through='sales.InvoicesSalesBody', to='products.items'),
        ),
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='typeTransactionID',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.typetransaction', verbose_name='نوع العملية'),
        ),
    ]
