# Generated by Django 4.2.3 on 2024-08-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_invoicessaleshead_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessalesbody',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=6, null=True, verbose_name='الكمية'),
        ),
    ]
