# Generated by Django 4.2.3 on 2024-08-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0013_alter_persons_languagesid_alter_persons_skillsid'),
        ('sales', '0016_inventory_alter_invoicessaleshead_inventoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessaleshead',
            name='currencyID',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.countries', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6, null=True, verbose_name='سعر الصرف'),
        ),
    ]
