# Generated by Django 4.2.3 on 2024-08-16 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_invoicessaleshead_currencyid_invoicessaleshead_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='التاريخ'),
        ),
    ]
