# Generated by Django 4.2.3 on 2024-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_invoicessaleshead_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
    ]
