# Generated by Django 4.2.3 on 2024-08-27 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_invoicessalesbody_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_customer', to='sales.customers', verbose_name='العميل'),
        ),
    ]
