# Generated by Django 4.2.3 on 2024-08-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_invoicessaleshead_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicessalesbody',
            name='inventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.inventory', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='invoicessalesbody',
            name='total_price_local_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر عملة محلية '),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان المستلم'),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='google_maps_location',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل'),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم هاتف المستلم'),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='phoneOther',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف آخر'),
        ),
        migrations.AddField(
            model_name='invoicessaleshead',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='invoicessalesbody',
            name='total_price_after_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي السعر بعد الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='description',
            field=models.TextField(blank=True, default='مبيعات', max_length=250, null=True, verbose_name='الوصف'),
        ),
    ]
