# Generated by Django 4.2.3 on 2024-09-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_invoicessalesbody_inventoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessalesbody',
            name='invoiceHeadID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_invoice', to='sales.invoicessaleshead'),
        ),
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attach_sales', verbose_name='المرفقات'),
        ),
    ]
