# Generated by Django 4.2.3 on 2024-09-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0007_alter_company_legalpersonid'),
        ('sales', '0024_alter_invoicessalesbody_invoiceheadid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicessaleshead',
            name='companyID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='companys.company'),
        ),
    ]
