# Generated by Django 4.2.3 on 2024-10-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0001_initial'),
        ('basicinfo', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='المخزن عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='المخزن إنجليزي')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف العنوان')),
                ('google_maps_location', models.URLField(blank=True, max_length=500, null=True, verbose_name='العنوان على خرائط قوقل')),
                ('phoneAdmin', models.CharField(blank=True, max_length=100, null=True, verbose_name='هاتف الموظف المسؤول')),
                ('administratorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorys_administrator_set', to='employees.employee', verbose_name='الموظف المسؤول')),
                ('cityID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorys_city_set', to='basicinfo.cities', verbose_name='المدينة')),
                ('companyID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorys_company_set', to='companys.company')),
                ('countryID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorys_country_set', to='basicinfo.countries', verbose_name='الدولة')),
                ('regionID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorys_region_set', to='basicinfo.region', verbose_name='المنطقة')),
                ('stateID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventorys_state_set', to='basicinfo.states', verbose_name='الولاية')),
            ],
        ),
    ]
