# Generated by Django 4.2.3 on 2024-10-16 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventorys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='متاح'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_inventory', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_inventory', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل'),
        ),
    ]
