# Generated by Django 4.2.3 on 2024-05-15 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrfntod', '0002_posts_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='linke',
            field=models.CharField(default=1, max_length=500, verbose_name='رابط البوست'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 15, 3, 23, 56, 909998, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ البوست'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=500, verbose_name='عنوان البوست'),
        ),
    ]
