# Generated by Django 4.2.3 on 2024-05-15 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrfntod', '0003_posts_linke_alter_posts_date_alter_posts_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='linke',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 15, 3, 24, 39, 732082, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ البوست'),
        ),
    ]
