# Generated by Django 4.2.3 on 2024-05-16 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrfntod', '0004_rename_linke_posts_link_alter_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dateHijri',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 5, 16, 3, 24, 37, 29500, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاريخ البوست'),
        ),
    ]
