# Generated by Django 4.2.3 on 2024-08-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0005_measuringunits_paymentmethods_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='itemCode',
            field=models.TextField(blank=True, null=True, verbose_name='كود الصنف'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='measuringUnitID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='basicinfo.measuringunits', verbose_name='معرف وحدة القياس'),
        ),
    ]
