# Generated by Django 4.2.3 on 2024-07-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_details_remove_orderdetails_productid'),
        ('basicinfo', '0007_color_size'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasingPrice', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر الشراء')),
                ('sellingPrice', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='سعر البيع')),
                ('name', models.CharField(max_length=100)),
                ('categoryID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('colorID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_color', to='basicinfo.color')),
                ('itemID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='products.category')),
                ('sizeID', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='basicinfo.size')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryTypeID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='products.categorytype'),
        ),
    ]
