# Generated by Django 4.2.3 on 2024-07-22 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinfo', '0007_color_size'),
        ('products', '0002_category_categorytype_items_itemsdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasingPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='سعر الشراء')),
                ('sellingPrice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='سعر البيع')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الصنف عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الصنف إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='مجموعة الصنف عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='مجموعة الصنف إنجليزي')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الصنف عربي')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الصنف إنجليزي')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryTypeID',
        ),
        migrations.RemoveField(
            model_name='items',
            name='categoryID',
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_itemsDetails', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ'),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_itemsDetails', to=settings.AUTH_USER_MODEL, verbose_name='المُعدِل'),
        ),
        migrations.AlterField(
            model_name='itemsdetails',
            name='colorID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='the_color', to='basicinfo.color', verbose_name='معرف اللون'),
        ),
        migrations.AlterField(
            model_name='itemsdetails',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الصنف'),
        ),
        migrations.AlterField(
            model_name='itemsdetails',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='itemsdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='صورة للصنف'),
        ),
        migrations.AlterField(
            model_name='itemsdetails',
            name='sizeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='size', to='basicinfo.size', verbose_name='معرف المقاس'),
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='itemgrop',
            name='itemTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_type', to='products.itemtype', verbose_name='معرف نوع الصنف'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemGropID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.itemgrop', verbose_name='معرف مجموعة الصنف'),
        ),
        migrations.AlterField(
            model_name='itemsdetails',
            name='itemID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='products.item', verbose_name='معرف الصنف'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
