# Generated by Django 4.2.3 on 2024-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_itemdetails_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='measuringUnitID',
            new_name='typeUnitID',
        ),
    ]
