# Generated by Django 4.2.3 on 2024-07-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0005_alter_company_owner_alter_companyuser_userid_and_more'),
        ('products', '0003_item_itemgrop_itemtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='companyID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='companys.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgrop',
            name='companyID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='companys.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgrop',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='companyID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='companys.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='companyID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='companys.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='sequence',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
