# Generated by Django 4.2.3 on 2024-07-24 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_color_size'),
        ('companys', '0005_alter_company_owner_alter_companyuser_userid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_qayd_posted_qayddetails_itemsdetailstid_and_more'),
        ('orders', '0003_order_itemsdetailsid_orderdetails_itemsdetailsid'),
        ('products', '0004_item_companyid_item_sequence_itemgrop_companyid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsDetails',
            new_name='ItemDetails',
        ),
    ]
