# Generated by Django 4.2.3 on 2024-08-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0007_rename_deliverymethods_typedelivery_and_more'),
        ('products', '0004_rename_measuringunitid_items_typeunitid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemGropID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.itemgrop', verbose_name='معرف مجموعة الصنف'),
        ),
        migrations.AlterField(
            model_name='items',
            name='typeUnitID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='basicinfo.typeunit', verbose_name='معرف وحدة القياس'),
        ),
    ]
