# Generated by Django 4.2.3 on 2024-07-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_itemsdetails_itemdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchasingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='سعر البيع'),
        ),
    ]
