# Generated by Django 4.2.3 on 2024-08-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_items_itemgropid_alter_items_typeunitid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['name_ar']},
        ),
    ]
