# Generated by Django 4.2.3 on 2024-08-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0011_targetgroup'),
        ('products', '0006_alter_item_purchasingprice_alter_item_sellingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='companyID',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='sequence',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='available',
            field=models.BooleanField(default=True, null=True, verbose_name='متاح'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='itemGropID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.itemgrop', verbose_name='معرف مجموعة الصنف'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الصنف عربي'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الصنف إنجليزي'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='purchasingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='سعر الشراء'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='colorID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='the_color', to='basicinfo.color', verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='sizeID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='size', to='basicinfo.size', verbose_name='المقاس'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
