# Generated by Django 4.2.3 on 2024-08-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinfo', '0013_languages_skills_person_google_maps_location_and_more'),
        ('products', '0007_remove_itemdetails_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='targetGroupID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='basicinfo.targetgroup', verbose_name='الفئة المستهدفة'),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='متاح'),
        ),
    ]
